seed: 42

data:
  dataset_path: null  # Uses HuggingFace dataset
  val_fraction: 0.1
  shuffle_seed: 42
  max_samples: 10     # Only 10 samples for testing
  max_eval_samples: 3  # Only 3 eval samples

model:
  base_model: gpt2
  tokenizer: gpt2
  max_length: 128     # Shorter for speed
  use_lora: false

optimizer:
  learning_rate: 5.0e-05
  weight_decay: 0.01

trainer:
  output_dir: artifacts/test_model
  epochs: 1
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 1
  warmup_steps: 0
  eval_strategy: steps
  eval_steps: 2
  save_strategy: steps
  save_steps: 2
  logging_steps: 1
  max_steps: 3        # Only 3 training steps
  bf16: false
  fp16: false

logging:
  use_wandb: false    # Disable W&B for testing
  project: null
  entity: null
  run_name: test-minimal-training
  sample_preview_interval: 1