seed: 42

data:
  dataset_path: null  # Uses HuggingFace dataset: cipher982/wine-text-126k
  val_fraction: 0.05
  shuffle_seed: 42
  max_samples: 100  # Small for quick testing
  max_eval_samples: 20

model:
  base_model: gpt2
  tokenizer: gpt2
  max_length: 256
  use_lora: false  # Simple fine-tuning for test

optimizer:
  learning_rate: 5.0e-05
  weight_decay: 0.01

trainer:
  output_dir: artifacts/test_model
  epochs: 1  # Just one epoch for test
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 1
  warmup_steps: 10
  eval_strategy: steps
  eval_steps: 50
  save_strategy: steps
  save_steps: 50
  logging_steps: 10
  max_steps: 10  # Quick pipeline validation
  bf16: false
  fp16: false

logging:
  use_wandb: false
  project: wine-test
  run_name: test-run
  sample_preview_interval: 50