seed: 321

data:
  dataset_path: data/processed/wine_training_dataset_v1.parquet
  val_fraction: 0.1
  shuffle_seed: 321
  max_samples: 64
  max_eval_samples: 16

model:
  base_model: sshleifer/tiny-gpt2
  tokenizer: sshleifer/tiny-gpt2
  max_length: 64
  use_lora: false
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05

optimizer:
  learning_rate: 5.0e-05
  weight_decay: 0.0

trainer:
  output_dir: artifacts/name_model_tiny
  epochs: 1
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 1
  warmup_steps: 0
  eval_strategy: "no"
  eval_steps: 50
  save_strategy: "no"
  save_steps: 50
  logging_steps: 5
  max_steps: 5
  bf16: false
  fp16: false

logging:
  use_wandb: false
  project: wine-modernization
  entity: null
  run_name: null
  sample_preview_interval: 20
