seed: 99

data:
  dataset_path: null
  val_fraction: 0.05
  apply_wine_type_heuristic: true
  shuffle_seed: 99

model:
  base_model: mistralai/Mistral-7B-Instruct-v0.3
  tokenizer: mistralai/Mistral-7B-Instruct-v0.3
  max_length: 512
  use_lora: true
  lora_r: 32
  lora_alpha: 64
  lora_dropout: 0.05

optimizer:
  learning_rate: 2.0e-05
  weight_decay: 0.01

trainer:
  output_dir: artifacts/desc_model
  epochs: 2
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 16
  warmup_steps: 200
  eval_strategy: steps
  eval_steps: 100
  save_strategy: steps
  save_steps: 100
  logging_steps: 20
  bf16: true
  fp16: false

logging:
  use_wandb: true
  project: wine-modernization
  entity: null
  run_name: description-generator-dev
  sample_preview_interval: 400

